### PR TITLE
Enhance scripts

### PR DESCRIPTION
**Pull request by Kjuly**
1. Build the Jekyll site directly to a temporary folder, no need to
   build then copy from one folder to another;
2. Rename branch name constants to SOURCE & SITE instead of source &
   built.

And update README.md appropriately, add .gitignore file.

### CODE REVIEW

**Comment by KingScooty** [comment]
@balevine is this PR going to get merged?

**Comment by balevine** [comment]
Wow. I totally missed this PR. I'm really sorry about that.

@Kjuly - If you're still interested in this, can you split this up into two separate PRs? One for the removal of the temp folder step and one for the `source` to `SOURCE` changes?

**Comment by Kjuly** [comment]
@balevine sure, will do it when I've got time :)

**Comment by Kjuly** [comment]
Hi @balevine , after u've merged #3 , let me send PR for the _"Build the Jekyll site directly to a temporary folder, no need to build then copy from one folder to another"_, or just merge this one. Thx :)

**Comment by Kjuly** [comment]
This one has conflicts, let me send another one for _"Build the Jekyll site directly to a temporary folder, no need to build then copy from one folder to another"_. :)

PR: #3 : _"Enhance scripts: Build the Jekyll site directly to a temporary folder"_

**Pull request closed without merging**
